# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 320, 441, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txteIleti = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txteIleti.setFont(font)
        self.txteIleti.setObjectName("txteIleti")
        self.verticalLayout_3.addWidget(self.txteIleti)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnBosluklariTemizle = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBosluklariTemizle.setFont(font)
        self.btnBosluklariTemizle.setObjectName("btnBosluklariTemizle")
        self.horizontalLayout_2.addWidget(self.btnBosluklariTemizle)
        self.spnbAdet = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spnbAdet.setFont(font)
        self.spnbAdet.setToolTipDuration(1)
        self.spnbAdet.setProperty("value", 1)
        self.spnbAdet.setObjectName("spnbAdet")
        self.horizontalLayout_2.addWidget(self.spnbAdet)
        self.btnGonder = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGonder.setFont(font)
        self.btnGonder.setObjectName("btnGonder")
        self.horizontalLayout_2.addWidget(self.btnGonder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 441, 301))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lneKullaniciMailAdresi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneKullaniciMailAdresi.setFont(font)
        self.lneKullaniciMailAdresi.setObjectName("lneKullaniciMailAdresi")
        self.verticalLayout.addWidget(self.lneKullaniciMailAdresi)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lneKullaniciMailSifresi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneKullaniciMailSifresi.setFont(font)
        self.lneKullaniciMailSifresi.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneKullaniciMailSifresi.setObjectName("lneKullaniciMailSifresi")
        self.verticalLayout.addWidget(self.lneKullaniciMailSifresi)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lneMailinGidecegiAdres = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneMailinGidecegiAdres.setFont(font)
        self.lneMailinGidecegiAdres.setObjectName("lneMailinGidecegiAdres")
        self.verticalLayout.addWidget(self.lneMailinGidecegiAdres)
        self.btnBoslukDoldurma = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnBoslukDoldurma.setFont(font)
        self.btnBoslukDoldurma.setObjectName("btnBoslukDoldurma")
        self.verticalLayout.addWidget(self.btnBoslukDoldurma)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lneMailKonusu = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lneMailKonusu.setFont(font)
        self.lneMailKonusu.setObjectName("lneMailKonusu")
        self.verticalLayout.addWidget(self.lneMailKonusu)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(750, 10, 261, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAdresKaydet = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAdresKaydet.setFont(font)
        self.btnAdresKaydet.setObjectName("btnAdresKaydet")
        self.verticalLayout_2.addWidget(self.btnAdresKaydet)
        self.lneKaydedilecekMail = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lneKaydedilecekMail.setObjectName("lneKaydedilecekMail")
        self.verticalLayout_2.addWidget(self.lneKaydedilecekMail)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(480, 10, 258, 611))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblMailler = QtWidgets.QTableWidget(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tblMailler.setFont(font)
        self.tblMailler.setRowCount(25)
        self.tblMailler.setColumnCount(1)
        self.tblMailler.setObjectName("tblMailler")
        item = QtWidgets.QTableWidgetItem()
        self.tblMailler.setItem(0, 0, item)
        self.tblMailler.horizontalHeader().setDefaultSectionSize(225)
        self.tblMailler.horizontalHeader().setMinimumSectionSize(49)
        self.tblMailler.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_4.addWidget(self.tblMailler)
        self.btnKayitliMailSil = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnKayitliMailSil.setFont(font)
        self.btnKayitliMailSil.setObjectName("btnKayitliMailSil")
        self.verticalLayout_4.addWidget(self.btnKayitliMailSil)
        self.btnCikis = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCikis.setFont(font)
        self.btnCikis.setObjectName("btnCikis")
        self.verticalLayout_4.addWidget(self.btnCikis)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(836, 610, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBosluklariTemizle.setText(_translate("MainWindow", "Boşlukları Temizle"))
        self.btnGonder.setText(_translate("MainWindow", "Gönder"))
        self.label_4.setText(_translate("MainWindow", "Mail adresiniz:"))
        self.label_3.setText(_translate("MainWindow", "Şifreniz:"))
        self.label_2.setText(_translate("MainWindow", "Mailin gideceği adres:"))
        self.btnBoslukDoldurma.setText(_translate("MainWindow", "Seçili mail bilgilerini doldur"))
        self.label_5.setText(_translate("MainWindow", "Mailin konusu:"))
        self.label.setText(_translate("MainWindow", "İleti:"))
        self.btnAdresKaydet.setText(_translate("MainWindow", "Mail adresini kaydet"))
        __sortingEnabled = self.tblMailler.isSortingEnabled()
        self.tblMailler.setSortingEnabled(False)
        self.tblMailler.setSortingEnabled(__sortingEnabled)
        self.btnKayitliMailSil.setText(_translate("MainWindow", "Seçili kayıtlı mailleri sil"))
        self.btnCikis.setText(_translate("MainWindow", "Uygulamadan çık"))
        self.label_6.setText(_translate("MainWindow", "Designed by Simo Hayha"))

